### ISSUE TITLE
Add sbt to bbop jenkins slaves

### ISSUE THREAD

**Issue by cmungall** [geneontology/ansible-machine-bootstrap#8]
Required for this job: https://build.berkeleybop.org/job/extract-grin-traits/

**Comment by kltm** [comment]
Likely with http://www.scala-sbt.org/release/docs/Installing-sbt-on-Linux.html to track updates.
Will hit after current apt-dater issues cleared.

**Comment by jnguyenx** [comment]
I did that for the monarch-mme server, might be helpful:
https://github.com/monarch-initiative/monarch-devops/blob/master/ansible/ohsu-migration/roles/monarch-mme/tasks/main.yml#L9

**Comment by kltm** [comment]
We mostly try to avoid the direct commands, as those have changed over time. The direct ansible module method is like:
```yaml
## SBT to help make JVM dev more tolerable.
## Get repo key.
- name: sbt (scala build tool) repo key
  apt_key: id=642AC823 keyserver=hkp://keyserver.ubuntu.com:80 state=present
## Get sbt repo, then recent version.
- name: get sbt repo
  apt_repository: repo='deb https://dl.bintray.com/sbt/debian /'
- name: install sbt
  apt: pkg=sbt state=present
```
